#!/usr/bin/env python3
"""B5 — add sample solutions to all 18 SAQs and 9 LEQs."""
import json, re
from pathlib import Path

ROOT = Path(__file__).parent.parent
TARGETS = [
    ROOT / 'js' / 'data' / 'apush_frq.js',
    ROOT / 'electron' / 'js' / 'data' / 'apush_frq.js',
]

SAQ_SOLUTIONS = {
    'apush-saq-u1-01': {
        'a': 'Indigenous peoples resisted and complicated the encomienda system in multiple ways. Some Native communities fled Spanish-controlled areas, retreating to remote frontier regions where encomenderos could not easily reach them. Others engaged in deliberate work slowdowns, feigned illness, or destroyed tools and crops to reduce their productivity as forced laborers. In some regions, Indigenous leaders negotiated directly with Spanish officials or the Crown, exploiting divisions between encomenderos and the Catholic Church to win limited protections.',
        'b': 'Old World diseases such as smallpox, measles, and typhus devastated Indigenous populations throughout the Americas, killing an estimated 50-90% of the pre-contact population within a century of European arrival. This demographic catastrophe directly destroyed the encomienda labor supply, since the system depended on extracting tribute and labor from large Indigenous communities. As populations collapsed, encomenderos could no longer meet their obligations to the Crown or sustain agricultural and mining operations, prompting the Spanish to experiment with the repartimiento system and eventually accelerate the importation of enslaved Africans.',
        'c': 'A key difference between the Spanish experience in the Aztec and Inca empires was the degree to which pre-existing administrative hierarchies facilitated or complicated colonial control. In central Mexico, Spanish conquerors were able to co-opt Aztec tributary networks relatively quickly because the Aztec empire had already accustomed subject peoples to paying tribute to a central authority; the Spanish simply substituted themselves at the top of that hierarchy. In the Andes, the Inca state had been more directly integrated, meaning that its collapse created a more significant administrative vacuum, and persistent revolts such as the Neo-Inca resistance at Vilcabamba demonstrated that Andean peoples had greater capacity for sustained organized resistance than many Mesoamerican groups.',
    },
    'apush-saq-u1-02': {
        'a': 'The encomienda system undermined centralized Spanish Crown authority because encomenderos in the Americas accumulated so much wealth and power that they increasingly acted as independent lords rather than loyal royal servants. The distance from Spain made enforcement of royal edicts nearly impossible, and encomenderos openly defied the New Laws of 1542 which sought to limit their privileges and protect Indigenous laborers. In Peru, this defiance escalated into open revolt led by Gonzalo Pizarro, demonstrating that the very system intended to extend royal authority had created a powerful colonial aristocracy capable of challenging it.',
        'b': 'Demographic collapse from disease eliminated the large Indigenous labor pools that made encomiendas profitable, forcing the Spanish Crown to restructure colonial labor. As encomiendas became economically unviable, the Crown used this crisis to reassert control, replacing the system with the repartimiento, which gave royal officials rather than private encomenderos direct authority over Indigenous labor drafts. This structural change transferred power back toward the colonial bureaucracy and away from the encomendero class, weakening the private aristocracy that had grown so difficult to govern.',
        'c': 'A meaningful difference between Spanish colonization of the former Aztec and Inca territories was the pace of administrative consolidation. In New Spain (Mexico), the Spanish built Mexico City directly atop Tenochtitlan and quickly established a functioning viceroyalty by the 1530s, in part because Aztec administrative personnel and tribute records could be adapted to Spanish purposes. In Peru, the Spanish faced a far longer period of instability, including civil wars among the conquistadors and prolonged armed resistance from the Neo-Inca state, meaning that effective colonial administration was not firmly established until the 1570s under Viceroy Toledo.',
    },
    'apush-saq-u2-05': {
        'a': 'A key development that complicated the sustainability of indentured servitude in the Chesapeake was the growing population of freed servants who had completed their indentures but found themselves landless and economically desperate. By the mid-seventeenth century, the best tobacco land along the tidal rivers had been claimed by established planters, leaving freed servants with no means to achieve the economic independence they had been promised. This growing class of landless, armed, and resentful men created a volatile social situation that planters recognized as a direct threat to colonial stability.',
        'b': 'The headright system gave fifty acres of land to anyone who paid the passage of an immigrant to Virginia, which meant wealthy planters and merchants accumulated vast tracts of tidewater land by importing servants. When those servants completed their indentures, they were entitled to freedom dues including tools and sometimes land, but the best land was already monopolized, forcing them to the western frontier or into tenancy. Crowded onto marginal frontier land and blocked from participation in the tobacco economy, these freed servants became politically radicalized, providing the social base for Bacon\'s Rebellion in 1676.',
        'c': 'A significant difference between the Chesapeake and New England following the social unrest of the late seventeenth century was in labor systems. Chesapeake planters, frightened by the interracial coalition that had joined Bacon\'s Rebellion, systematically shifted from indentured servitude to racial chattel slavery, which provided a permanently subordinated labor force without the problem of freedom dues or land expectations. New England, by contrast, relied on family labor, artisan production, and a mixed economy of farming and trade that did not require large-scale bound labor, allowing the region to maintain social order through town institutions and Puritan communal structures rather than through racial hierarchy.',
    },
    'apush-saq-u2-06': {
        'a': 'Bacon\'s Rebellion was not simply a frontier conflict between settlers and Native Americans but involved a significant interracial and interclass coalition that complicated the planter elite\'s ability to maintain social control. Bacon\'s forces included not only white frontier settlers and indentured servants but also a substantial number of enslaved and free Black Virginians who joined the rebellion seeking freedom and land. The willingness of Black and white poor Virginians to fight together against the colonial establishment revealed deep class tensions that transcended racial lines and terrified the planter elite far more than the rebellion\'s military component.',
        'b': 'As tobacco cultivation expanded in the Chesapeake tidewater, the most productive riverfront land was monopolized by established planters who used the headright system to accumulate vast holdings. Freed indentured servants, who had been promised economic opportunity, found themselves unable to acquire viable farmland and were forced onto marginal frontier soils or into tenancy on great planters\' estates. Unable to grow enough tobacco to pay their debts or achieve independence, and blocked from the political representation that might have addressed their grievances, these men had little to lose and everything to gain from armed rebellion.',
        'c': 'After Bacon\'s Rebellion, Chesapeake planters responded to labor instability by transitioning systematically to racial chattel slavery, importing large numbers of enslaved Africans whose permanent, hereditary unfreedom eliminated the problem of a dangerous class of freed servants. New England, facing different pressures in the same period — including King Philip\'s War and witchcraft hysteria — maintained order through Puritan communal institutions, town meetings, and a more diversified economy that did not produce the same class of landless, armed poor. This divergence reveals that the Chesapeake\'s instability was structural, rooted in a plantation economy dependent on bound labor, while New England\'s challenges were more contingent and could be absorbed by its more egalitarian social structures.',
    },
    'apush-saq-u3-08': {
        'a': 'The colonial resistance movement complicated the simple argument about taxation without representation by revealing that many colonists themselves denied the very liberties they claimed to be defending. Enslaved people petitioned colonial legislatures arguing that the same principles justifying resistance to British tyranny required the abolition of slavery, exposing the hypocrisy of a movement led largely by slaveholders. Women who organized boycotts and contributed to the resistance effort similarly found that the revolutionary rhetoric of natural rights and consent did not extend to them, suggesting the crisis was as much about who would exercise power in America as about abstract principles of liberty.',
        'b': 'During the era of salutary neglect, colonial assemblies had grown accustomed to raising their own taxes, passing their own laws, and governing local affairs with minimal interference from London. Over decades, this practical self-governance created an expectation that these powers were colonial rights rather than royal concessions. When Britain reversed course after 1763 and asserted parliamentary supremacy over the colonies through measures like the Stamp Act and Townshend Acts, colonists experienced this not as a new policy but as a violation of a constitutional arrangement they believed had been established through long practice — making their resistance feel like the defense of existing liberties rather than a revolutionary demand for new ones.',
        'c': 'Colonial Patriots of the 1760s-1770s feared the arbitrary power of a distant Parliament and king that could tax and legislate without their consent — the threat was external tyranny imposed from across the Atlantic. Anti-Federalists during the ratification debates of 1787-1788 feared a different danger: a powerful central government controlled by a distant elite that would absorb the powers of the states and ultimately oppress ordinary citizens from within. Both groups feared concentrated power, but the Patriots feared foreign domination while the Anti-Federalists feared that the new republic\'s own leaders might replicate the very tyranny they had fought to escape.',
    },
    'apush-saq-u3-09': {
        'a': 'Colonial resistance complicated the defense of traditional English liberties when colonists began to argue not merely for their rights as Englishmen but for natural rights belonging to all people regardless of nationality. Thomas Paine\'s Common Sense rejected the framework of English constitutional law entirely, arguing that monarchy was an inherently corrupt institution and that American independence was justified on universal principles rather than English precedent. This radicalization of the argument from legal rights to natural rights meant colonists were no longer simply defending an existing constitution but were constructing an entirely new political philosophy that could not be contained within the British imperial framework.',
        'b': 'The inability of Congress under the Articles of Confederation to levy taxes or regulate interstate commerce left the national government dependent on voluntary state contributions that were frequently withheld, creating a fiscal crisis that threatened to collapse the union. When Shays\' Rebellion in 1786 demonstrated that the federal government lacked the power to protect creditors or suppress domestic insurrection, elite founders concluded that a stronger central government was essential to protect property rights and maintain social order. The specter of democratic excess — of state legislatures responding to debtors\' demands by issuing cheap paper money and canceling debts — convinced men like Madison and Hamilton that the Constitution\'s stronger executive and bicameral legislature were necessary safeguards against popular tyranny.',
        'c': 'Anti-Federalists feared that the proposed Constitution would create a distant national government dominated by a wealthy elite that would use its broad powers to oppress ordinary citizens — their concern was that centralized power in the hands of men unlike themselves would produce tyranny. Earlier colonial critics of Parliamentary authority had feared something similar but more straightforwardly: that a legislature in which they had no representation was taxing and legislating them without consent. The Anti-Federalists\' anxiety was more complex — they feared not just a distant government but also the document\'s lack of a bill of rights, its allowing a standing army, and its weakening of state sovereignty as a check on national ambition.',
    },
    'apush-saq-u4-12': {
        'a': 'The market revolution complicated reform movements by intensifying economic inequality even as it generated the surplus wealth that middle-class reformers needed to fund their activities. As factory production displaced skilled artisans and created a growing industrial working class, many workers found themselves too economically precarious to participate in moral reform organizations that demanded time, dues, and religious commitment. The very prosperity that sustained the reform impulse in Northern cities was built on a system of wage labor that reformers often failed to challenge, revealing the limits of a movement that addressed individual moral failings rather than structural economic injustice.',
        'b': 'The growth of wage labor in the Northeast created a class of white working men who feared that the abolition of slavery in the South would flood Northern labor markets with free Black workers willing to accept lower wages. This economic anxiety translated into widespread hostility to abolitionism among Northern working-class communities, who perceived antislavery advocacy as a threat to their own economic security rather than a moral cause. Labor organizations frequently adopted explicitly racist positions, and mob violence against abolitionist speakers and presses in Northern cities was often carried out by working-class men who felt economically threatened by the prospect of Black freedom and competition.',
        'c': 'Both the women\'s rights movement and the abolitionist movement used moral and religious arguments rooted in the Second Great Awakening\'s emphasis on individual conscience and human equality before God, but they faced different institutional barriers to political change. Abolitionists could appeal to existing religious organizations, had sympathetic constituencies in free Black communities, and could draw on a network of churches and antislavery societies for organizational support, though they faced violent opposition in both North and South. Women reformers, by contrast, were frequently excluded from the very reform organizations they helped build — abolitionist societies regularly denied women full membership and public speaking roles — meaning that women had to construct entirely separate institutions before they could translate their moral arguments into political demands.',
    },
    'apush-saq-u4-13': {
        'a': 'Some participants in the Second Great Awakening reinforced rather than challenged the emerging capitalist order by promoting values of self-discipline, sobriety, punctuality, and individual responsibility that aligned perfectly with the demands of industrial employers. The temperance movement, for example, framed alcohol consumption as a moral failing of working-class men rather than a structural response to economic misery, thereby pathologizing the poor rather than challenging the conditions of their labor. Similarly, benevolent organizations that provided charity to the urban poor often conditioned their assistance on recipients\' willingness to adopt middle-class Protestant behavior, reinforcing the ideology that poverty resulted from individual moral failure rather than systemic inequality.',
        'b': 'Organizations such as the American Tract Society and the American Bible Society used the new technology of steam-powered printing presses to produce religious and reform literature at unprecedented scale and distribute it through a national network of volunteers and paid agents. This infrastructure allowed reform messages to reach rural areas and small towns far from the urban centers where reform movements originated, creating a national audience for causes like temperance, antislavery, and Sabbatarian legislation. The same evangelical networks that distributed Bibles also circulated antislavery newspapers and reform periodicals, effectively creating a communications infrastructure for moral reform that paralleled and sometimes preceded the political organizing of reform movements.',
        'c': 'Northern white women reformers faced significant barriers to public participation in reform organizations, including social norms against women speaking in mixed-gender public settings and explicit exclusion from leadership positions in organizations like the American Anti-Slavery Society. However, their social position as educated, middle-class women gave them access to domestic networks, churches, and female literary societies through which they could organize and fundraise. Free Black women reformers faced all these same gender barriers plus the additional obstacles of racial discrimination from white-dominated reform organizations and the constant vulnerability of being free Black women in a society that offered them almost no legal protection, meaning they often had to build entirely separate institutions to pursue their reform goals.',
    },
    'apush-saq-u5-16': {
        'a': 'The Fugitive Slave Act of 1850, included as part of the Compromise, actually intensified Northern opposition to slavery rather than resolving sectional tensions, because it required Northern citizens and officials to actively participate in the capture and return of freedom-seeking people. Many Northerners who had been willing to tolerate slavery as a distant Southern institution found themselves morally implicated by a law that made them complicit in returning people to bondage on Northern streets. The Act energized the antislavery movement, drove thousands of Black Americans to flee to Canada, and produced dramatic rescue attempts in cities like Boston and Syracuse that became celebrated acts of resistance, undermining the compromise\'s goal of sectional peace.',
        'b': 'The Compromise of 1877 ended Reconstruction by trading the disputed presidential election of Rutherford Hayes for the withdrawal of federal troops from the South, effectively ending federal enforcement of the Fourteenth and Fifteenth Amendments. Without federal military protection, Southern states systematically dismantled Black political participation through violence, economic coercion, and eventually legal mechanisms like literacy tests, poll taxes, and grandfather clauses. The Compromise demonstrated that Northern Republicans had prioritized economic reconciliation and sectional reunion over the constitutional rights of Black Southerners, leaving the enforcement of the Reconstruction amendments entirely to states that were explicitly hostile to them.',
        'c': 'A meaningful similarity between formerly enslaved people during Reconstruction and free Black Northerners in the antebellum period was their shared focus on achieving legal recognition of citizenship and the political rights that flowed from it. Both groups petitioned legislatures, organized conventions, published newspapers, and appealed to the constitutional principles of the founding generation to argue for their inclusion in the American political community. A key difference, however, was that Reconstruction-era Black political leaders also sought land redistribution and economic independence — demands rooted in the specific experience of people who had created wealth through their labor without compensation — while free Black Northerners in the antebellum period focused more on dismantling legal discrimination and achieving equal access to education and the courts.',
    },
    'apush-saq-u5-17': {
        'a': 'The Supreme Court\'s interpretation of the Fourteenth Amendment in the Slaughterhouse Cases (1873) and United States v. Cruikshank (1876) severely limited the amendment\'s protective scope before it could be effectively applied. In Cruikshank, the Court ruled that the federal government could only protect citizens from state violations of their rights, not from private violence — meaning that white supremacist organizations like the Ku Klux Klan could terrorize Black Southerners without triggering federal intervention. This judicial construction essentially gutted the enforcement provisions of the Reconstruction amendments by removing federal jurisdiction over the widespread private violence that was the primary mechanism of Black disenfranchisement and oppression in the South.',
        'b': 'The Compromise of 1877 resolved the disputed Hayes-Tilden presidential election by giving the presidency to Republican Rutherford Hayes in exchange for a promise to withdraw federal troops from the remaining Reconstruction states of South Carolina and Louisiana. Once those troops were removed, the last Republican Reconstruction governments in the South collapsed, eliminating the political infrastructure that had protected Black voting rights and officeholding. Without federal troops to enforce the Fourteenth and Fifteenth Amendments, Southern Democrats used violence, economic coercion, and eventually legal disfranchisement mechanisms to systematically remove Black citizens from political life, demonstrating that constitutional rights without federal enforcement were effectively unenforceable.',
        'c': 'Both formerly enslaved people during Reconstruction and free Black Northerners in the antebellum period sought to expand their legal and civic standing within the American political system rather than to overturn that system entirely, appealing to founding-era ideals of equality and citizenship. A key difference was that Reconstruction-era Black political demands were more materially focused: formerly enslaved people called for land redistribution, economic reparations for unpaid labor, and access to education as prerequisites for meaningful freedom, recognizing that legal rights without economic independence were insufficient. Free Black Northerners in the antebellum period, living in a more commercially integrated economy, focused more on removing racial barriers to education, employment, and legal equality, since many had already achieved some degree of economic independence.',
    },
    'apush-saq-u6-20': {
        'a': 'The American Federation of Labor complicated the goal of broad worker solidarity by organizing exclusively along craft lines and explicitly excluding unskilled workers, recent immigrants from Southern and Eastern Europe, women, and most Black workers from membership. Samuel Gompers justified this exclusionary strategy as pragmatic — skilled craftsmen had the greatest bargaining leverage and could win concrete gains — but it left the vast majority of industrial workers unorganized and created deep divisions between the AFL\'s relatively privileged craft workers and the poorly paid laborers of mass production industries. The AFL\'s willingness to accept racial exclusion in affiliated unions in exchange for organizational stability revealed that the labor movement\'s vision of solidarity was limited by the racial and ethnic hierarchies of Gilded Age America.',
        'b': 'The arrival of millions of Southern and Eastern European immigrants in the 1880s and 1890s created a large pool of low-wage workers willing to take industrial jobs at wages that undercut the earnings of established workers, which the AFL interpreted as a threat to its members\' standard of living. The AFL responded by supporting immigration restrictions, lobbying for Chinese exclusion laws, and organizing only skilled craft workers rather than the new immigrant workforce in mass production industries. This strategy left the AFL with a predominantly native-born, Northwestern European membership and widened the divide between the organized skilled minority and the unorganized immigrant majority of the industrial working class.',
        'c': 'The Knights of Labor pursued an inclusive, industrial vision of working-class organization that welcomed all workers regardless of skill, race, gender, or ethnicity, and sought not merely higher wages but a fundamental transformation of the wage system through producer cooperatives and land reform. The American Federation of Labor, by contrast, adopted a craft-based, exclusive model focused on skilled workers in specific trades, pursuing the pragmatic goals of higher wages, shorter hours, and better conditions through collective bargaining without challenging capitalism itself. This difference reflected competing visions of working-class power: the Knights believed workers could reorganize the economy on cooperative principles, while the AFL accepted the capitalist framework and sought only to improve labor\'s position within it.',
    },
    'apush-saq-u6-21': {
        'a': 'The Gilded Age labor movement was deeply divided along racial and ethnic lines, with the American Federation of Labor explicitly excluding Black workers from most affiliated craft unions and supporting legislation restricting Asian immigration. These exclusions undermined the solidarity the labor movement claimed to represent and left the majority of industrial workers — unskilled, immigrant, or non-white — without union protection. The AFL\'s exclusionary policies reflected and reinforced the racial hierarchies of Gilded Age America, demonstrating that the labor movement\'s vision of worker solidarity was in practice limited to a relatively privileged stratum of skilled white workers.',
        'b': 'Carnegie\'s strategy of vertical integration, which brought under single corporate ownership the iron ore mines, coking coal fields, railroads, and steel mills, eliminated the independent suppliers and subcontractors whose existence had given skilled workers leverage in contract negotiations. Before vertical integration, steelworkers could threaten to disrupt production at a critical bottleneck in the supply chain; after it, Carnegie controlled the entire production process and could simply shut down a plant, wait out a strike, and reopen with non-union labor without disrupting the broader system. The Homestead Strike of 1892 demonstrated this dynamic, as Carnegie Steel used the Pinkerton agency and eventually the Pennsylvania National Guard to break the Amalgamated Association of Iron and Steel Workers permanently.',
        'c': 'Both the Knights of Labor and the Populist movement challenged the concentration of economic power in the Gilded Age by arguing that ordinary producers — workers and farmers — were being systematically exploited by a parasitic class of financiers, railroad corporations, and monopolists. A meaningful difference was in their proposed solutions and constituencies: the Knights focused on the urban and industrial working class and advocated for producer cooperatives and the abolition of the wage system, while the Populists spoke primarily for indebted farmers and demanded specific government interventions including railroad regulation, a graduated income tax, and an inflated money supply. The Knights largely collapsed after 1886, while the Populist Party briefly became a significant electoral force before being absorbed into the Democratic Party in 1896.',
    },
    'apush-saq-u7-24': {
        'a': 'The New Deal\'s promise of universal economic relief was significantly undermined by the systematic exclusion of agricultural and domestic workers from key programs including Social Security, the National Labor Relations Act, and the Fair Labor Standards Act. These exclusions were not accidental; they were written into legislation at the insistence of Southern Democratic congressmen who controlled key committee chairmanships and refused to support programs that would give Black workers economic alternatives to the exploitative sharecropping and domestic service arrangements that underpinned the Southern racial economy. Since the overwhelming majority of Black workers in the South were employed in exactly these excluded categories, the New Deal\'s most significant benefits effectively bypassed Black Americans most in need of relief.',
        'b': 'Southern Democrats held disproportionate power in Congress through the seniority system, which gave committee chairmanships to the longest-serving members from the most electorally stable districts — which in the one-party South meant conservative white Democrats who faced no electoral competition. These chairmen of the Agriculture, Labor, and Finance committees wielded veto power over New Deal legislation and used it to ensure that programs affecting labor relations and social insurance excluded the agricultural and domestic occupations that employed most Southern Black workers. Roosevelt, needing Southern Democratic votes to pass his entire legislative agenda, accepted these exclusions rather than risk losing the broader coalition that made the New Deal possible.',
        'c': 'Northern industrial workers benefited enormously from New Deal programs: the National Labor Relations Act protected their right to organize, the Fair Labor Standards Act established minimum wages and maximum hours, and unemployment insurance and Social Security provided a safety net for industrial workers and their families. Black agricultural laborers in the South experienced the New Deal very differently: the Agricultural Adjustment Act paid subsidies to landowners who reduced crop acreage, but the payments rarely reached sharecroppers and tenant farmers, who were often displaced from the land rather than helped. The result was that the New Deal simultaneously strengthened the economic position of the unionized industrial working class while leaving the rural Black South largely untouched and in some respects worse off than before.',
    },
    'apush-saq-u7-25': {
        'a': 'The Agricultural Adjustment Act deepened racial inequality in the South by directing crop reduction payments to landowners rather than to the sharecroppers and tenant farmers who actually worked the land, the majority of whom were Black. As landowners received federal payments to take land out of production, they had both the financial incentive and the legal power to evict sharecroppers and consolidate their holdings, displacing hundreds of thousands of Black farm families who had no legal recourse. The New Deal programs that were supposed to rescue the rural poor instead accelerated the displacement of Black agricultural workers, concentrating federal benefits in the hands of the white landowning class that had historically exploited them.',
        'b': 'Southern Democrats exercised their power primarily through committee chairmanships controlled by the seniority system, and they made clear to Roosevelt that they would block his entire legislative agenda if programs threatened the racial and economic order of the South. The specific mechanism was the exclusion of agricultural and domestic occupations from federal labor protections and social insurance — occupations that were not accidentally the primary employment categories for Black workers in the South. This was not a failure of enforcement but a deliberate legislative design, written into statutes as the price of Southern Democratic support for the broader New Deal coalition.',
        'c': 'Urban industrial workers gained access to the National Labor Relations Act\'s guarantee of collective bargaining rights, unemployment insurance under the Social Security Act, and wage and hour protections under the Fair Labor Standards Act — a package of protections that fundamentally strengthened their economic position relative to employers. Southern Black agricultural laborers were explicitly excluded from all three of these signature programs, meaning they remained entirely at the mercy of landowners and employers with no federal protection for their wages, working conditions, or right to organize. The difference in outcomes reveals how the New Deal\'s benefits were filtered through the racial and political economy of the South, producing a two-tier welfare state that reinforced rather than challenged existing racial hierarchies.',
    },
    'apush-saq-u8-28': {
        'a': 'McCarthyism undermined the democratic principles America claimed to defend against Soviet communism by deploying the same tools of political repression — guilt by association, secret informants, loyalty oaths, and blacklisting — that characterized totalitarian regimes. The Senate Permanent Subcommittee on Investigations under McCarthy used congressional immunity to make accusations without evidence, destroying careers and reputations without the due process protections that American democracy guaranteed. The contradiction was not lost on critics: a country proclaiming freedom of thought and expression as its defining virtues was systematically punishing dissent, unorthodox political associations, and personal beliefs through mechanisms that bore a disturbing resemblance to the Communist Party purges it condemned.',
        'b': 'The fall of China to Mao\'s Communist forces in 1949 and the outbreak of the Korean War in 1950 created a political environment in which any Democratic official who questioned McCarthy\'s charges risked being labeled soft on communism, silencing potential opposition. Truman\'s own administration had established the Federal Employee Loyalty Program in 1947 in response to Republican pressure, which had the unintended effect of legitimizing the premise that communist infiltration of the government was a real and serious problem. McCarthy exploited this defensive posture, knowing that Democrats who challenged his evidence would face the political accusation that they were protecting communist subversives, making sustained institutional opposition to his campaign politically too costly for most Democratic politicians to risk.',
        'c': 'McCarthyism targeted primarily government employees, academics, and entertainment industry figures on the basis of alleged Communist Party membership or associations, operating largely through congressional hearings and public exposure rather than criminal prosecution, and its victims were disproportionately white intellectuals and professionals. COINTELPRO, by contrast, specifically targeted Black civil rights organizations, American Indian activists, Puerto Rican independence movements, and antiwar groups, and operated covertly through illegal surveillance, infiltration, forged documents, and deliberate disruption rather than public hearings. The shift from McCarthyite exposure to COINTELPRO\'s covert destabilization reflected both a more sophisticated tool of repression and a more explicitly racial dimension to the government\'s definition of subversion.',
    },
    'apush-saq-u8-29': {
        'a': 'The Korean War complicated Truman\'s ability to present containment as a coherent strategy when General Douglas MacArthur publicly challenged civilian authority by lobbying for an expanded war against China, including the possible use of nuclear weapons, in direct defiance of the President\'s limited war policy. Truman\'s dismissal of MacArthur in April 1951 was constitutionally correct but politically catastrophic, as MacArthur returned to a hero\'s welcome and congressional Republicans used the episode to portray Truman as weak and indecisive. The episode exposed the fundamental tension within containment between its defensive logic — preventing communist expansion without triggering a wider war — and the demands of American political culture for decisive victory rather than indefinite stalemate.',
        'b': 'McCarthy\'s anti-communist campaign created a political environment in which any Democratic official who appeared insufficiently aggressive against communism risked career-ending accusations of being a communist sympathizer or worse, which meant that Truman\'s defense of a limited war in Korea could be portrayed as appeasement. The "Who Lost China?" narrative that Republicans used to attack Truman after 1949 was directly applied to Korea, where a stalemate that fell short of victory was framed not as a successful defense of containment but as evidence that Democrats were unwilling or unable to win the Cold War. This rhetorical environment made it impossible for Truman to present the Korean armistice as an acceptable outcome, contributing to his historically low approval ratings and his decision not to seek reelection in 1952.',
        'c': 'The Korean War\'s stalemate damaged Truman and the Democrats primarily through the mechanism of military frustration — Americans had expected victory and got a cease-fire at roughly the starting line — which contributed to Eisenhower\'s landslide victory in 1952 but did not permanently define Democratic Party politics. The Vietnam War\'s escalation under Johnson had more lasting and structural consequences for the Democratic Party, splitting it between the antiwar left represented by Eugene McCarthy and Robert Kennedy and the Cold War liberal establishment, a rupture that was dramatized at the 1968 Chicago convention and fundamentally reshaped the party\'s coalition for decades. The Vietnam trauma produced a lasting Democratic skepticism of military interventionism that Korea had not, making it the more historically significant party-defining moment.',
    },
    'apush-saq-u9-32': {
        'a': 'Clinton\'s signing of the Personal Responsibility and Work Opportunity Reconciliation Act of 1996, which effectively ended the federal welfare entitlement established by the New Deal, alienated the liberal wing of the Democratic Party that had long defended the social safety net as a core party commitment. Similarly, Clinton\'s support for NAFTA over the strong opposition of labor unions — one of the party\'s core constituencies — deepened the sense among working-class Democrats that their interests were being sacrificed for the preferences of corporate donors and free-trade economists. These centrist policy choices demonstrated that triangulation could win electoral victories while fracturing the Democratic coalition, generating the progressive disillusionment that would fuel primary challenges and third-party votes for years afterward.',
        'b': 'Newt Gingrich\'s Contract with America nationalized the 1994 midterms by framing them as a referendum on Clinton\'s first term and presenting a unified conservative legislative agenda that gave Republican candidates a coherent message in every district. After winning the House majority, Gingrich used procedural tactics — limiting committee deliberation, centralizing power in the Speaker\'s office, and pursuing aggressive oversight investigations of the Clinton administration — to maximize partisan conflict rather than seek bipartisan compromise. The two government shutdowns of 1995-96 demonstrated that Republicans were willing to paralyze the federal government to force spending cuts, establishing a new template for using budget confrontations as political weapons that would define congressional polarization for the following three decades.',
        'c': 'Clinton-era polarization was driven significantly by cultural and personal animosity — the politics of the culture wars over abortion, gay rights, and gun control, combined with the personal attacks and ultimately the impeachment proceedings surrounding Clinton\'s private conduct. Obama-era polarization was driven more by structural and ideological forces: the rise of the Tea Party in 2009-2010 reflected a grassroots conservative mobilization against government spending and the Affordable Care Act that was reinforced by partisan media ecosystems, gerrymandered districts, and the self-sorting of Americans into politically homogeneous communities. While Clinton faced intense partisan opposition, the institutional norms of bipartisan governance still held in many areas; by the Obama era, those norms had significantly eroded, making routine legislative functions like confirming executive appointments and passing budgets sites of unprecedented partisan conflict.',
    },
    'apush-saq-u9-33': {
        'a': 'Clinton\'s triangulation strategy deepened rather than reduced polarization in several respects. By adopting Republican positions on welfare reform, crime policy, and deficit reduction, Clinton did neutralize those specific issues electorally but also legitimized a rightward shift in the Democratic Party that angered the liberal base without winning genuine Republican cooperation. The Republican response to triangulation was not moderation but escalation — rather than accepting Clinton\'s concessions as evidence of good faith, conservative Republicans pursued increasingly aggressive oversight investigations and ultimately impeachment, suggesting that polarization was driven not merely by policy disagreement but by fundamental rejection of Clinton\'s legitimacy as president.',
        'b': 'Gingrich\'s Contract with America provided a nationalized Republican platform that unified the party behind specific legislative commitments, transforming midterm congressional elections from local contests into national referendums on the president. After taking the House majority, Gingrich reformed House procedures to centralize power and limit the committee independence that had enabled bipartisan deal-making, ensuring that Republican legislation advanced strictly along party lines. The willingness to shut down the federal government rather than compromise on spending levels established a new norm of treating routine governance functions as opportunities for political leverage, creating a cycle of brinkmanship that made compromise increasingly difficult even when both parties had substantive incentives to reach deals.',
        'c': 'Clinton-era polarization operated primarily through personal and cultural conflict — the politics of impeachment, culture war controversies, and the rise of partisan media represented largely by talk radio — while the institutional capacity for bipartisan legislating remained partially intact, as demonstrated by Clinton\'s ability to pass welfare reform, NAFTA, and budget agreements with Republican support. Obama-era polarization became more structural and parliamentary in character: the Tea Party movement institutionalized the norm that cooperation with the opposing party\'s president was a form of betrayal, Senate Republicans normalized the routine filibustering of executive appointments and legislation, and the 2010 redistricting cycle produced House districts so safe for one party that members faced more electoral risk from primary challenges than from general elections, creating powerful incentives toward ideological purity over legislative accomplishment.',
    },
}

LEQ_SOLUTIONS = {
    'apush-leq-u1-03': {
        'thesis': 'While Old World diseases were the proximate cause of Indigenous demographic collapse, Spanish colonial policies — including forced labor, family separation, and the destruction of agricultural systems — both accelerated biological mortality and prevented population recovery, making colonial extraction equally responsible for the catastrophic decline.',
        'contextualization': 'In 1492, the Americas were home to an estimated 50-100 million people organized in complex societies ranging from the Aztec and Inca empires to smaller chiefdoms and hunting-gathering communities. European contact introduced not only armed conquest but also new disease pathogens to populations with no prior exposure and therefore no acquired immunity — a biological reality that would shape every dimension of colonial encounter.',
        'evidence_point1': 'Spanish colonial policies directly caused mortality independent of disease: the mita labor system in Andean silver mines at Potosi killed workers through exposure, overwork, and mercury poisoning; the encomienda required tribute payments that disrupted subsistence agriculture, causing famine; and military campaigns systematically destroyed communities, food stores, and social structures that had supported population recovery after earlier epidemics.',
        'evidence_point2': 'Disease was the single greatest killer: smallpox killed perhaps half the Aztec population before the final siege of Tenochtitlan; successive epidemics of measles, typhus, and influenza reduced Central Mexican population from roughly 25 million in 1519 to fewer than 2 million by 1600. These losses were driven by biological factors — lack of immunity, population density, and the novelty of the pathogens — that were not directly caused by colonial policy.',
        'analysis': 'The distinction between biological causation and colonial acceleration is crucial. Disease was necessary but not sufficient for the scale of collapse observed; Spanish policies prevented the demographic recovery that typically follows epidemic mortality by disrupting the social, agricultural, and family structures that allow populations to rebuild. The comparison with Indigenous peoples of North America, who suffered similar epidemics but in many cases maintained population recovery, suggests that the intensity of extraction under Spanish colonialism produced a uniquely catastrophic outcome.',
    },
    'apush-leq-u2-07': {
        'thesis': 'Bacon\'s Rebellion transformed the Chesapeake labor system primarily by demonstrating the danger of a class of landless, armed, free white men — a fear of interracial class alliance that drove planters to replace indentured servitude with racial chattel slavery as a more controllable and self-reproducing labor system.',
        'contextualization': 'By the 1670s, the Chesapeake tobacco economy had produced significant wealth for large planters while creating a growing class of landless, economically frustrated men who had completed their indentures but could find neither land nor economic opportunity. This social tension was embedded in a broader Atlantic world in which race as a legal category was still being constructed and in which English servants and African workers sometimes labored side by side and developed cross-racial solidarities.',
        'evidence_point1': 'The interracial character of Bacon\'s forces — including both white servants and some enslaved Black Virginians — demonstrated to planters that a shared class grievance could overcome racial distinctions, and the prolonged resistance of Bacon\'s men after Bacon himself died showed that the rebellion had deeper structural roots than one charismatic leader. This specific fear of poor white and Black alliance drove the transition more directly than simple economic calculation.',
        'evidence_point2': 'The economic case for slavery had been building independently: William Fitzhugh\'s 1684 letter to the Royal African Company shows planters calculating that enslaved labor for life was more cost-effective than repeatedly cycling through indentured servants who required freedom dues and eventually became potential rebels. The Royal African Company\'s loss of its monopoly in 1698 dramatically reduced the price of enslaved people, making the transition economically feasible precisely when social control demands made it politically necessary.',
        'analysis': 'The rebellion accelerated a transition that had already begun for economic reasons, but its specific contribution was ideological: it helped crystallize the concept of a fixed racial divide as a tool of social control. By conferring symbolic status advantages on even poor white Virginians — access to the militia, legal protections unavailable to Black workers, the psychological wage of racial superiority — planters undermined the class solidarity that had made Bacon\'s coalition possible, producing a racial hierarchy that would shape American society for centuries.',
    },
    'apush-leq-u3-10': {
        'thesis': 'While economic grievances provided the immediate triggers for colonial resistance, the American Revolution was driven more fundamentally by a genuine ideological transformation in which colonists developed a new conception of representative government, natural rights, and popular sovereignty that made continued membership in the British empire intellectually and politically unacceptable.',
        'contextualization': 'The Seven Years\' War (1754-1763) transformed Britain\'s relationship with its American colonies: Britain emerged from the war with massive debt and a vastly expanded empire in North America, while American colonists emerged with military experience, continental connections, and a growing sense of their own capabilities. Britain\'s decision to pay for imperial defense through colonial taxation reversed decades of salutary neglect and provoked resistance that quickly evolved from a legal dispute about parliamentary authority into a fundamental rethinking of the basis of legitimate government.',
        'evidence_point1': 'The ideological transformation is visible in the escalation of colonial arguments: the initial response to the Stamp Act (1765) framed resistance in terms of traditional English constitutional rights — no taxation without representation. By 1776, the Declaration of Independence had abandoned the argument from English rights entirely and claimed universal natural rights, asserting that governments derive their just powers from the consent of the governed and that any government destructive of natural rights may be altered or abolished. This was a genuinely revolutionary philosophical development, not merely a legal dispute about tax policy.',
        'evidence_point2': 'The economic grievances were real but insufficient as an explanation: many colonial merchants actually profited from smuggling and the disruption of imperial trade regulations, and the actual tax burden imposed by the Stamp Act and Townshend duties was relatively light compared to what Englishmen in Britain paid. The intensity of the colonial response — boycotts, committees of correspondence, and ultimately armed resistance — was disproportionate to the economic harm, suggesting that the colonists\' fundamental objection was to the principle of Parliamentary sovereignty over them, not merely to specific tax burdens.',
        'analysis': 'The ideological interpretation is strengthened by the fact that colonial leaders continued to deepen their philosophical commitments even after many economic grievances were addressed: Britain repealed the Stamp Act in 1766 and most Townshend duties in 1770, but resistance continued and intensified. The colonists\' insistence on the Declaratory Act\'s repeal — which simply asserted Parliament\'s right to legislate for the colonies in all cases — showed that what they were defending was a principle of self-governance, not a specific economic interest.',
    },
    'apush-leq-u4-14': {
        'thesis': 'Political and economic developments between 1800 and 1840 expanded democratic participation primarily for white men while simultaneously deepening the exclusion of women, Black Americans, and Indigenous peoples, revealing that Jacksonian democracy was not a universal expansion of freedom but a restructuring of power that benefited one group partly at the expense of others.',
        'contextualization': 'The early nineteenth century saw the United States transformed by the market revolution, which linked a formerly subsistence economy into a national and international commercial network, and by the Second Great Awakening, which democratized religious life and produced the reform impulse. These changes created new possibilities for some Americans while intensifying the exploitation of others, particularly as cotton cultivation expanded westward on the basis of enslaved labor and the dispossession of Native peoples.',
        'evidence_point1': 'The period saw genuine expansion of white male democracy: property requirements for voting were eliminated in most states by the 1830s, voter turnout rose dramatically, political parties developed new techniques of mass mobilization through barbecues, parades, and partisan newspapers, and the spoils system gave ordinary white men access to government positions previously reserved for the educated elite. Jackson\'s presidency itself symbolized this shift — a self-made frontiersman rather than a Virginia gentleman or Massachusetts lawyer.',
        'evidence_point2': 'The same period witnessed the active limitation of others\' participation: the Indian Removal Act of 1830 dispossessed tens of thousands of Indigenous people from their eastern homelands; the tightening of slave codes across the South restricted the already-limited freedoms of enslaved and free Black people; and the Seneca Falls Convention of 1848 emerged precisely because women\'s exclusion from political life was being reaffirmed rather than challenged by the democratic enthusiasm of the era.',
        'analysis': 'The expansion of white male democracy and the deepening of racial and gender exclusion were not coincidental but structurally connected: the symbolic equality among white men was partly sustained by the sharp legal and social distinctions between them and everyone else, and the cotton economy\'s profitability — which created the wealth fueling the market revolution — depended on the continued exclusion of enslaved Black people from the political community. Jacksonian democracy was genuinely democratic for white men partly because it was simultaneously exclusionary for everyone else.',
    },
    'apush-leq-u5-18': {
        'thesis': 'The escalating sectional crisis between 1845 and 1860 did represent a fundamental breakdown of the political system, but this breakdown was caused not simply by disagreement over slavery\'s expansion but by the inability of existing political institutions — the two-party system, the Senate\'s balance of power, and the Supreme Court\'s authority — to contain a conflict in which the two sections held irreconcilable positions on the nature of property, labor, and constitutional rights.',
        'contextualization': 'The Missouri Compromise of 1820 had established a framework for managing sectional conflict over slavery by maintaining a geographic boundary and a Senate balance between slave and free states. The Mexican War and its territorial acquisitions reopened the question of slavery\'s expansion in a context where the old compromises no longer held, and the political parties that had previously transcended sectional divisions — the Whigs and Democrats — collapsed under the pressure of an issue that could not be neutralized through logrolling and coalition building.',
        'evidence_point1': 'The institutional breakdown accelerated through a series of escalating crises: the Compromise of 1850 required Daniel Webster to sacrifice his political career and still produced Northern fury over the Fugitive Slave Act; the Kansas-Nebraska Act destroyed the Missouri Compromise and produced "Bleeding Kansas," a small civil war that presaged the larger one; and the Dred Scott decision destroyed the possibility of a congressional settlement by declaring that Congress had no authority to restrict slavery anywhere in the territories.',
        'evidence_point2': 'The collapse of the Whig Party and the emergence of the explicitly sectional Republican Party demonstrated that the political system could no longer contain the slavery issue within a framework of national parties. When Lincoln won the presidency in 1860 without a single Southern electoral vote, Southern leaders concluded that their minority position within the constitutional system was permanent — the population growth of the free states meant they would never again control the presidency through the existing political process.',
        'analysis': 'The crisis was a genuine breakdown rather than simply a failure of political will because the underlying conflict was not susceptible to political compromise: Southern slaveholders required not merely the toleration but the legal protection and potential expansion of slavery, while the free-labor ideology of the Republican Party held that slavery was a moral wrong that must be placed on a path to extinction. These positions could not be permanently split the difference through legislation, which is why each successive compromise simply generated a new and more explosive crisis rather than resolving the underlying conflict.',
    },
    'apush-leq-u6-22': {
        'thesis': 'While industrial consolidation transformed the American economy by concentrating unprecedented wealth and productive power in the hands of large corporations, it simultaneously generated the political and social movements — labor unions, Populism, and Progressive reform — that would ultimately force the state to impose regulatory constraints on corporate power, making the Gilded Age a period of transformation in both directions.',
        'contextualization': 'The decades following the Civil War saw the United States transformed from a primarily agricultural society into the world\'s largest industrial economy, driven by railroad construction, steel production, oil refining, and the integration of a continental market. This transformation was enabled by federal land grants to railroads, high protective tariffs that shielded American industry from foreign competition, and a legal environment that treated corporations as persons with constitutional rights while offering workers minimal protection.',
        'evidence_point1': 'Industrial consolidation produced genuinely transformative economic gains: Carnegie\'s vertical integration of the steel industry drove down the price of steel while increasing production dramatically, enabling the construction of railroads, bridges, and skyscrapers that would have been impossible at earlier prices. Standard Oil\'s control of 90% of American refining capacity allowed Rockefeller to achieve efficiencies that lowered kerosene prices for consumers even while eliminating competition. The productivity gains of the Gilded Age created a material abundance that, however unequally distributed, transformed everyday life.',
        'evidence_point2': 'The same consolidation generated severe political and economic inequality that threatened democratic governance: railroad rate discrimination destroyed small farmers\' ability to compete; company towns gave employers total control over workers\' lives; and the concentration of wealth in the hands of a few dozen families gave those families disproportionate influence over legislatures, courts, and presidents. The Supreme Court\'s use of the Fourteenth Amendment to protect corporations from state regulation while denying its protections to Black Southerners demonstrated how thoroughly the legal system had been captured by corporate interests.',
        'analysis': 'The Gilded Age\'s significance for political life was not simply that it created inequality but that it revealed the inadequacy of nineteenth-century governmental structures — designed for an agrarian republic — to regulate an industrial economy. The Populist and Progressive movements that emerged in response were not anti-capitalist but pro-regulatory: they accepted industrial capitalism while demanding that it be subjected to democratic accountability. The Sherman Antitrust Act (1890), Interstate Commerce Commission, and eventually the Progressive Era reforms of the early twentieth century all represented the political system\'s belated adaptation to industrial reality.',
    },
    'apush-leq-u7-26': {
        'thesis': 'The federal government\'s response to economic and social crises changed substantially between the Progressive Era and the New Deal, as the New Deal permanently established the principle of federal responsibility for citizens\' economic welfare, but both periods were defined by the same fundamental tension between the imperative to respond to suffering and the political and constitutional limits imposed by federalism, congressional conservatism, and business opposition.',
        'contextualization': 'The Progressive Era emerged from the social dislocations of the Gilded Age and operated in a constitutional environment that was skeptical of federal power over the economy. The New Deal emerged from the worst economic catastrophe in American history — by 1933 a quarter of the workforce was unemployed — in a political environment where the scale of suffering had discredited laissez-faire economics and created a temporary coalition willing to accept unprecedented federal intervention.',
        'evidence_point1': 'The Progressive Era established important precedents for federal economic regulation: the Sherman Antitrust Act was used under Roosevelt to break up Northern Securities; the Pure Food and Drug Act and Meat Inspection Act established federal regulatory authority over consumer products; the Federal Reserve Act created a central bank; and the Sixteenth and Seventeenth Amendments authorized an income tax and direct election of senators. These reforms expanded federal power significantly but left the basic structure of the private economy intact.',
        'evidence_point2': 'The New Deal went substantially further by asserting federal responsibility for unemployment, old-age security, and workers\' right to organize — commitments that the Progressive Era had not made. The Social Security Act, National Labor Relations Act, and Securities and Exchange Commission represented a qualitative expansion of the federal role from regulating market abuses to providing a social safety net and restructuring the relationship between labor and capital. These changes survived legal challenges and political opposition to become permanent features of American governance.',
        'analysis': 'The continuity between the two periods is as significant as the change: both were limited by the power of business interests, the constitutional constraints of federalism, and the political necessity of maintaining Southern Democratic support by avoiding challenges to racial hierarchy. The New Deal\'s exclusion of agricultural and domestic workers from its key provisions replicated the Progressive Era\'s failure to address racial inequality in the South. In both periods, the expansion of federal power was real but partial, shaped by the same political constraints that limited reform to what a majority coalition of diverse interests could accept.',
    },
    'apush-leq-u8-30': {
        'thesis': 'While domestic political pressures significantly shaped American Cold War foreign policy — particularly in intensifying rhetorical anti-communism and limiting presidents\' diplomatic flexibility — the more fundamental drivers of policy were the ideological commitment to containing Soviet expansion and the strategic calculations produced by the specific military and political crises that Cold War competition generated.',
        'contextualization': 'The United States emerged from World War II as the world\'s dominant economic and military power but faced an ideologically hostile Soviet Union that had acquired atomic weapons by 1949 and was rapidly expanding its influence in Eastern Europe and Asia. American foreign policy was conducted in a domestic political environment profoundly shaped by McCarthyism, the China lobby, and competing visions of American global responsibility that made the costs and benefits of specific foreign policy choices subject to intense domestic scrutiny.',
        'evidence_point1': 'Domestic pressures demonstrably constrained presidential freedom of action: Truman\'s inability to negotiate a Korean armistice at the 38th parallel in 1951 without suffering catastrophic domestic political attack illustrates how McCarthyite politics forced presidents to pursue more aggressive military stances than strategic calculation would have recommended. Similarly, Kennedy\'s decision not to accept a trade of Turkish missiles for Cuban missiles publicly during the Cuban Missile Crisis was driven partly by domestic political concerns about appearing weak to Soviet pressure.',
        'evidence_point2': 'Strategic ideology drove the most consequential foreign policy decisions regardless of domestic politics: the Truman Doctrine (1947) and Marshall Plan (1948) were bold commitments made before domestic anti-communism had reached its McCarthy-era intensity, reflecting a genuine strategic judgment that Soviet expansion must be contained; the decision to intervene in Korea in 1950 was made on strategic grounds — establishing the credibility of containment commitments — not primarily in response to domestic political pressure; and Nixon\'s opening to China in 1972 defied the expectations of the domestic anti-communist constituency that had sustained Republican foreign policy since the late 1940s.',
        'analysis': 'The domestic and strategic explanations are not fully separable because the domestic political culture of anti-communism both reflected and reinforced the ideological content of containment strategy. McCarthyism was not an external constraint on a neutral strategic process but an expression of the same ideological framework — that communist expansion represented an existential threat to American freedom — that drove policy. The most accurate interpretation is that domestic politics and ideology interacted: domestic pressure generally pushed policy toward greater militarism and rhetorical toughness while occasionally blocking diplomatic flexibility, but the fundamental strategic commitment to containment was genuine and would have driven an active global foreign policy regardless of the domestic political environment.',
    },
    'apush-leq-u9-34': {
        'thesis': 'While American global power commitments — Cold War military spending, the War on Terror, and NATO obligations — shaped domestic priorities through their budgetary and political consequences, internal forces including demographic change, partisan realignment, and economic transformation were more significant in determining the direction of American society between 1981 and 2012.',
        'contextualization': 'Reagan came to office in 1981 promising to simultaneously rebuild American military strength, cut taxes, and reduce domestic spending — goals whose internal contradictions would generate the largest peacetime deficits in American history and shape fiscal politics for the following three decades. The collapse of the Soviet Union in 1991 created a brief "peace dividend" moment before the September 11, 2001 attacks launched a new era of military commitment that would cost trillions of dollars and transform the political landscape.',
        'evidence_point1': 'Cold War military spending constrained domestic investment significantly: Reagan\'s defense buildup, funded by deficit spending rather than tax increases, produced structural deficits that limited the fiscal space for domestic programs throughout the 1980s and 1990s and drove the deficit politics that dominated the Clinton era. The post-9/11 wars in Afghanistan and Iraq, funded entirely by borrowing, created trillions in long-term obligations that constrained domestic spending debates during the Obama years and contributed to the Tea Party\'s anti-deficit mobilization.',
        'evidence_point2': 'Internal forces more fundamentally reshaped American society: the demographic transformation produced by immigration, particularly from Latin America and Asia, was reshaping the electorate and the workforce in ways that had profound political consequences — contributing to Obama\'s 2008 coalition — entirely independent of foreign policy. The deindustrialization of the Rust Belt, driven by globalization and technological change rather than military spending, created the economic dislocations that fueled populist politics on both left and right. The culture wars over abortion, gay rights, and immigration that dominated domestic politics from Reagan through Obama were driven by social and demographic change, not by foreign policy imperatives.',
        'analysis': 'The relationship between foreign commitments and domestic priorities worked in both directions but the causal primacy of internal forces is demonstrated by the fact that the most consequential domestic political developments of the period — the Reagan coalition, the rise of the Christian right, the Clinton third way, the Tea Party — were responses to internal social and economic changes rather than to foreign policy developments. Foreign policy\'s main domestic impact was fiscal, limiting the resources available for domestic investment, but the direction in which those limited resources were deployed was determined by domestic political coalitions that had their own independent logic.',
    },
}


def apply(frqs):
    added = 0
    all_solutions = {**SAQ_SOLUTIONS, **LEQ_SOLUTIONS}
    for frq in frqs:
        fid = frq.get('id')
        if fid in all_solutions and frq.get('sampleSolution') is None:
            frq['sampleSolution'] = all_solutions[fid]
            added += 1
    return added


def process(path):
    if not path.exists():
        print(f'  SKIP: {path}'); return
    text = path.read_text()
    m = re.search(r'=\s*(\[.*\])\s*;?\s*$', text, re.DOTALL)
    if not m:
        print(f'  ERROR parsing {path}'); return
    frqs = json.loads(m.group(1))
    n = apply(frqs)
    print(f'  added {n} sample solutions')
    path.write_text(text[:m.start(1)] + json.dumps(frqs, indent=2, ensure_ascii=False) + text[m.end(1):])
    print(f'  wrote {path.name}')


print('=== B5 sample solutions ===')
for t in TARGETS:
    print(f'\n{t}:')
    process(t)
print('\nDone.')
